# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163a0484ca8892cbb1b35f9eb2b05f87d024d6243586383648d147bf53767842567ca42e2aa31e6374eca398013588d748f03777060c681ec7c9fa6341984e0f

test:
  secret_key_base: 4b9891b57a322b0a9c3a7b89eb92c4d80e08b95e71a8b408f008c9bfa04ffbde99830f0f1fb1c93b47f4606f5c7fb7710de53fdd6aafa4edf50ef0082651483d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
